import Head from 'next/head'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Jammin&apos;</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Test</main>

      <footer>Foot</footer>
    </div>
  )
}

export default Home
